---
name: Run tests on Ubuntu

on:
  workflow_call:
    inputs:
      targets: {required: true, type: string}
      os: {required: true, type: string}
      subversion: {required: true, type: string}
      dependencies: {required: true, type: string}

env:
  INPUT_SVNARC: ${{ fromJson(inputs.subversion).archive }}

jobs:

  swig-py:
    if: ${{ contains(fromJson(inputs.targets), 'swig-py') }}
    runs-on: ${{ matrix.os }}
    needs: prepare
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
        python-version: ['3.12', '3.11', '3.10', '3.9', '3.8', '3.7', '3.6', '3.5', '2.7']
        exclude:
          - {os: ubuntu-22.04, python-version: '3.6'}
          - {os: ubuntu-22.04, python-version: '3.5'}

    env:
      MATRIX_OS: ${{ matrix.os }}
      MATRIX_PYVER: ${{ matrix.python-version }}

    steps:
    - name: Set up libraries
      uses: actions/cache@v3
      with:
        path: ~/svn
        key: ${{ matrix.os }}--svn-run${{ github.run_number }}.${{ github.run_attempt }}

    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ !startsWith(matrix.python-version, '2.') }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout subversion
      if: ${{ fromJson(inputs.subversion).repository }}
      uses: actions/checkout@v4
      with:
        repository: ${{ fromJson(inputs.subversion).repository }}
        ref: ${{ fromJson(inputs.subversion).ref }}
        path: subversion

    - name: Checkout py3c
      uses: actions/checkout@v4
      with:
        repository: encukou/py3c
        ref: ${{ fromJson(inputs.dependencies).py3c }}
        path: py3c

    - name: Set up archives cache
      if: ${{ fromJson(inputs.subversion).archive }}
      uses: actions/cache@v3
      with:
        path: arc
        fail-on-cache-miss: true
        enableCrossOsArchive: true
        key: arc--${{ fromJson(inputs.subversion).archive }}

    - run: ./build.sh swig-py


  swig-rb:
    if: ${{ contains(fromJson(inputs.targets), 'swig-rb') }}
    runs-on: ${{ matrix.os }}
    needs: prepare
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
        ruby-version: ['3.3', '3.2', '3.1', '3.0', '2.7', '2.6', '2.5', '2.4']

    env:
      MATRIX_OS: ${{ matrix.os }}

    steps:
    - name: Set up libraries
      uses: actions/cache@v3
      with:
        path: ~/svn
        key: ${{ matrix.os }}--svn-run${{ github.run_number }}.${{ github.run_attempt }}

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout subversion
      if: ${{ fromJson(inputs.subversion).repository }}
      uses: actions/checkout@v4
      with:
        repository: ${{ fromJson(inputs.subversion).repository }}
        ref: ${{ fromJson(inputs.subversion).ref }}
        path: subversion

    - name: Set up archives cache
      if: ${{ fromJson(inputs.subversion).archive }}
      uses: actions/cache@v3
      with:
        path: arc
        fail-on-cache-miss: true
        enableCrossOsArchive: true
        key: arc--${{ fromJson(inputs.subversion).archive }}

    - run: ./build.sh swig-rb


  swig-pl:
    if: ${{ contains(fromJson(inputs.targets), 'swig-pl') }}
    runs-on: ${{ matrix.os }}
    needs: prepare
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
        perl-version: ['5.36', '5.34', '5.32', '5.30', '5.28', '5.26', '5.24', '5.22']

    env:
      MATRIX_OS: ${{ matrix.os }}

    steps:
    - name: Set up libraries
      uses: actions/cache@v3
      with:
        path: ~/svn
        key: ${{ matrix.os }}--svn-run${{ github.run_number }}.${{ github.run_attempt }}

    - name: Set up Perl ${{ matrix.perl-version }}
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl-version }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout subversion
      if: ${{ fromJson(inputs.subversion).repository }}
      uses: actions/checkout@v4
      with:
        repository: ${{ fromJson(inputs.subversion).repository }}
        ref: ${{ fromJson(inputs.subversion).ref }}
        path: subversion

    - name: Set up archives cache
      if: ${{ fromJson(inputs.subversion).archive }}
      uses: actions/cache@v3
      with:
        path: arc
        fail-on-cache-miss: true
        enableCrossOsArchive: true
        key: arc--${{ fromJson(inputs.subversion).archive }}

    - run: ./build.sh swig-pl


  javahl:
    if: ${{ contains(fromJson(inputs.targets), 'javahl') }}
    runs-on: ${{ matrix.os }}
    needs: prepare
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
        java-version: ['21', '17', '16', '11', '8']

    env:
      MATRIX_OS: ${{ matrix.os }}

    steps:
    - name: Set up libraries
      uses: actions/cache@v3
      with:
        path: ~/svn
        key: ${{ matrix.os }}--svn-run${{ github.run_number }}.${{ github.run_attempt }}

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: ${{ matrix.java-version }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout subversion
      if: ${{ fromJson(inputs.subversion).repository }}
      uses: actions/checkout@v4
      with:
        repository: ${{ fromJson(inputs.subversion).repository }}
        ref: ${{ fromJson(inputs.subversion).ref }}
        path: subversion

    - name: Set up archives cache
      if: ${{ fromJson(inputs.subversion).archive }}
      uses: actions/cache@v3
      with:
        path: arc
        fail-on-cache-miss: true
        enableCrossOsArchive: true
        key: arc--${{ fromJson(inputs.subversion).archive }}

    - run: ./build.sh javahl


  core:
    if: ${{ contains(fromJson(inputs.targets), 'core') }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}

    env:
      MATRIX_OS: ${{ matrix.os }}

    steps:
    - name: Set up libraries
      uses: actions/cache@v3
      with:
        path: ~/svn
        key: ${{ matrix.os }}--svn-run${{ github.run_number }}.${{ github.run_attempt }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout subversion
      if: ${{ fromJson(inputs.subversion).repository }}
      uses: actions/checkout@v4
      with:
        repository: ${{ fromJson(inputs.subversion).repository }}
        ref: ${{ fromJson(inputs.subversion).ref }}
        path: subversion

    - name: Set up archives cache
      if: ${{ fromJson(inputs.subversion).archive }}
      uses: actions/cache@v3
      with:
        path: arc
        fail-on-cache-miss: true
        enableCrossOsArchive: true
        key: arc--${{ fromJson(inputs.subversion).archive }}

    - run: ./build.sh all

    - name: Upload log files
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: log-core-${{ matrix.os }}
        path: 'subversion/*.log'


  prepare:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}

    env:
      MATRIX_OS: ${{ matrix.os }}

    steps:
    - name: Set up libraries
      uses: actions/cache@v3
      with:
        path: ~/svn
        key: ${{ matrix.os }}--svn-run${{ github.run_number }}.${{ github.run_attempt }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout subversion
      if: ${{ fromJson(inputs.subversion).repository }}
      uses: actions/checkout@v4
      with:
        repository: ${{ fromJson(inputs.subversion).repository }}
        ref: ${{ fromJson(inputs.subversion).ref }}
        path: subversion

    - name: Set up archives cache
      if: ${{ fromJson(inputs.subversion).archive }}
      uses: actions/cache@v3
      with:
        path: arc
        fail-on-cache-miss: true
        enableCrossOsArchive: true
        key: arc--${{ fromJson(inputs.subversion).archive }}

    - run: ./build.sh install
